"""init schema

Revision ID: 6cd2924763df
Revises: 
Create Date: 2026-05-09 16:48:33.895481

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6cd2924763df'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papers',
    sa.Column('arxiv_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('authors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('pdf_url', sa.Text(), nullable=False),
    sa.Column('categories', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_page_text', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('arxiv_id')
    )
    op.create_index(op.f('ix_papers_published_at'), 'papers', ['published_at'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('platform', 'user', name='run_kind'), nullable=False),
    sa.Column('status', sa.Enum('running', 'success', 'failed', name='run_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('n_fetched', sa.Integer(), nullable=False),
    sa.Column('n_evaluated', sa.Integer(), nullable=False),
    sa.Column('n_failed', sa.Integer(), nullable=False),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('deepseek_key_encrypted', sa.Text(), nullable=True),
    sa.Column('tz', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('keywords', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('top_n', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configs_user_id'), 'configs', ['user_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('paper_id', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('novelty', sa.Integer(), nullable=False),
    sa.Column('practicality', sa.Integer(), nullable=False),
    sa.Column('rigor', sa.Integer(), nullable=False),
    sa.Column('relevance', sa.Integer(), nullable=False),
    sa.Column('keywords', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('affiliations', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('summary_zh', sa.Text(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.arxiv_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('paper_id')
    )
    op.create_index(op.f('ix_evaluations_evaluated_at'), 'evaluations', ['evaluated_at'], unique=False)
    op.create_index(op.f('ix_evaluations_prompt_version'), 'evaluations', ['prompt_version'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('config_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('email', name='sub_channel'), nullable=False),
    sa.Column('send_at_local', sa.Time(), nullable=False),
    sa.Column('last_sent_on', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('unsubscribe_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['configs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unsubscribe_token')
    )
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_evaluations_prompt_version'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_evaluated_at'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_configs_user_id'), table_name='configs')
    op.drop_table('configs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('runs')
    op.drop_index(op.f('ix_papers_published_at'), table_name='papers')
    op.drop_table('papers')
    # ### end Alembic commands ###
